//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Detalle_Exquisito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_producto
    {
        public string Cod_Producto_Detalle { get; set; }
        public byte[] foto { get; set; }
        public string nombreProducto { get; set; }
        public string Descripcion { get; set; }
        public double precio { get; set; }
        public string Cod_Producto { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
