//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Detalle_Exquisito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Productos_Extras
    {
        public int Nro_DPE { get; set; }
        public string foto_Ubicacion { get; set; }
        public string descripcion { get; set; }
        public int ID_extra_Producto { get; set; }
        public int ID_detalle_Pedido { get; set; }
    
        public virtual Extra_Productos Extra_Productos { get; set; }
        public virtual detalle_Pedido detalle_Pedido { get; set; }
    }
}
