//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Detalle_Exquisito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int Id_Per { get; set; }
        public Nullable<int> ID_EmCar { get; set; }
    
        public virtual Cargo_Empleo Cargo_Empleo { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
