//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Detalle_Exquisito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operaciones_Menu
    {
        public int id_OpeMen { get; set; }
        public int rol_seleccion { get; set; }
        public int id_operaciones { get; set; }
    
        public virtual Operaciones Operaciones { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
