//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Detalle_Exquisito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string correo_Electronico { get; set; }
        public string contraseña { get; set; }
        public string estado { get; set; }
        public int rol { get; set; }
        public int ID_Persona { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Rol Rol1 { get; set; }
    }
}
